[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "~2.0"
futures = "0.1"
grpcio = "0.4"

[dependencies.raft]
git = "https://github.com/nolouch/raft-rs.git"
branch = "fix-read-index"
